Repository Async-Swift/AsyncSwift, pull requests merged in 2022-09, with the labels that each got.

#9 [Build] Universal Link Setting
  AsyncSwift/AsyncSwift.entitlements
  AsyncSwift/AsyncSwiftApp.swift
  README.md
  apple-app-site-association
Labels: Ready to Merge

#10 [Build] 배포 예정 계정의 certification으로 수동 빌드되도록 설정
  AsyncSwift.xcodeproj/project.pbxproj
Labels: In Review

#11 [Feat] Ticket Button을 누르면, Ticketing WebView 표시 구현
  AsyncSwift.xcodeproj/project.pbxproj
  AsyncSwift/Extensions/WebView.swift
  AsyncSwift/Views/TicketingView.swift
Labels: In Review

#13 [FEAT] Change Flip Animation more Naturally
  AsyncSwift/Views/StampView.swift
Labels: In Review

#19 [Feat] Add appIcon
  AsyncSwift/Assets.xcassets/AppIcon.appiconset/100.png
  AsyncSwift/Assets.xcassets/AppIcon.appiconset/1024.png
  AsyncSwift/Assets.xcassets/AppIcon.appiconset/114.png
  AsyncSwift/Assets.xcassets/AppIcon.appiconset/120.png
  AsyncSwift/Assets.xcassets/AppIcon.appiconset/144.png
  AsyncSwift/Assets.xcassets/AppIcon.appiconset/152.png
  AsyncSwift/Assets.xcassets/AppIcon.appiconset/167.png
  AsyncSwift/Assets.xcassets/AppIcon.appiconset/180.png
  AsyncSwift/Assets.xcassets/AppIcon.appiconset/20.png
  AsyncSwift/Assets.xcassets/AppIcon.appiconset/29.png
  AsyncSwift/Assets.xcassets/AppIcon.appiconset/40.png
  AsyncSwift/Assets.xcassets/AppIcon.appiconset/50.png
  AsyncSwift/Assets.xcassets/AppIcon.appiconset/57.png
  AsyncSwift/Assets.xcassets/AppIcon.appiconset/58.png
  AsyncSwift/Assets.xcassets/AppIcon.appiconset/60.png
  AsyncSwift/Assets.xcassets/AppIcon.appiconset/72.png
  AsyncSwift/Assets.xcassets/AppIcon.appiconset/76.png
  AsyncSwift/Assets.xcassets/AppIcon.appiconset/80.png
  AsyncSwift/Assets.xcassets/AppIcon.appiconset/87.png
  AsyncSwift/Assets.xcassets/AppIcon.appiconset/Contents.json
Labels: In Review

#14 [HotFix] StampView Change to IVO pattern
  AsyncSwift.xcodeproj/project.pbxproj
  AsyncSwift/Observed/AppData.swift
  AsyncSwift/Observed/StampView+Observed.swift
  AsyncSwift/Views/StampView.swift
Labels: Ready to Merge

#20 [Refactor] TicketingView를 IVOPattern에 맞게 수정
  AsyncSwift.xcodeproj/project.pbxproj
  AsyncSwift/Observed/TicketingView+Observed.swift
  AsyncSwift/Views/TicketingView.swift
Labels: In Review

#22 [Feat] JsonParsing
  AsyncSwift.xcodeproj/project.pbxproj
  AsyncSwift.xcodeproj/project.xcworkspace/xcuserdata/kiminsub.xcuserdatad/UserInterfaceState.xcuserstate
  AsyncSwift/AppDelegate.swift
  AsyncSwift/AsyncSwiftApp.swift
  AsyncSwift/Identifiable/EventResponse.swift
  AsyncSwift/Identifiable/Mock.swift
  AsyncSwift/Info.plist
  AsyncSwift/Models/EventModel.swift
  AsyncSwift/Models/SessionModel.swift
  AsyncSwift/Observed/EventDetailView+Observed.swift
  AsyncSwift/Observed/EventView+Observed.swift
  AsyncSwift/Observed/SessionView+Observed.swift
  AsyncSwift/Views/EventDetailView.swift
  AsyncSwift/Views/EventView.swift
  AsyncSwift/Views/SessionView.swift
Labels: Ready to Merge

#28 [Fix] Ticketing View를 로컬 데이터가 아닌 JSON으로 가져온 데이터를 표시하도록 수정
  AsyncSwift.xcodeproj/project.pbxproj
  AsyncSwift/Assets.xcassets/Colors/skeletonBackground.colorset/Contents.json
  AsyncSwift/Assets.xcassets/Seminar002Ticket.imageset/Contents.json
  AsyncSwift/Assets.xcassets/Seminar002Ticket.imageset/Seminar002.pdf
  AsyncSwift/Assets.xcassets/UpcomingConference001.imageset/Contents.json
  AsyncSwift/Assets.xcassets/UpcomingConference001.imageset/UpcomingConference001.pdf
  AsyncSwift/Extensions/Color+.swift
  AsyncSwift/Models/Ticketing.swift
  AsyncSwift/Observed/TicketingView+Observed.swift
  AsyncSwift/Views/TicketingView.swift
Labels: In Review

#30 [FIX] Tab Item의 오탈자를 수정
  AsyncSwift/Observed/AppData.swift
Labels: Ready to Merge

#29 [FEAT] Ticket이 존재하지 않을 때, 티켓이 존재하지 않는다는 화면을 표시
  AsyncSwift/Assets.xcassets/Colors/emptyTicketViewBackground.colorset/Contents.json
  AsyncSwift/Assets.xcassets/Colors/emptyTicketViewForeground.colorset/Contents.json
  AsyncSwift/Extensions/Color+.swift
  AsyncSwift/Models/Ticketing.swift
  AsyncSwift/Observed/TicketingView+Observed.swift
  AsyncSwift/Views/TicketingView.swift
Labels: In Review

#31 [FEAT] GitHub Repository의 PR Template를 추가
  pull_request_template.md
Labels: In Review

#38 [FIX] TicketingView Image Loading 사실을 알기쉽도록 스켈레톤의 색 대비를 높임.
  AsyncSwift/Assets.xcassets/Colors/skeletonBackground.colorset/Contents.json
Labels: Bug

#37 [HotFix] Miss TabView Selection
  .DS_Store
  .well-known/apple-app-site-association
  AsyncSwift/Info.plist
  AsyncSwift/Observed/AppData.swift
  AsyncSwift/Views/MainTabView.swift
  apple-app-site-association
Labels: Ready to Merge

#42 [HotFix] 앱 재시동후 Stamp가 보이지 않은 문제
  .well-known/apple-app-site-association
  AsyncSwift/Observed/AppData.swift
  CNAME
Labels: Ready to Merge

#43 Release v1.0.2
  .well-known/apple-app-site-association
  AsyncSwift.xcodeproj/project.pbxproj
  AsyncSwift.xcodeproj/project.xcworkspace/xcuserdata/kiminsub.xcuserdatad/UserInterfaceState.xcuserstate
  AsyncSwift/Observed/AppData.swift
  CNAME
Labels: Ready to Merge

#44 Release v1.0.2
  AsyncSwift.xcodeproj/project.pbxproj
  AsyncSwift.xcodeproj/project.xcworkspace/xcuserdata/kiminsub.xcuserdatad/UserInterfaceState.xcuserstate
Labels: Ready to Merge
